//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqliteDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produce
    {
        public long Id { get; set; }
        public string ProduceName { get; set; }
        public decimal Cost { get; set; }
    }
}
